### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by qiang-zhang-neu** [ANTsX/ANTsPy#105]
I find there is a wheel: https://pypi.org/project/antspyx/
Thus, I install antspy by: pip install antspyx. 
The installation is OK, however, error happen when I import it:
```

>>> import ants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\ants\__init__.py", line 7, in <module>
    from .core import *
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\ants\core\__init__.py", line 2, in <module>
    from .ants_image import *
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\ants\core\ants_image.py", line 27, in <module>
    from .. import utils, registration, segmentation, viz
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\ants\utils\__init__.py", line 2, in <module>
    from .bias_correction import *
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\ants\utils\bias_correction.py", line 9, in <module>
    from . import process_args as pargs
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\ants\utils\process_args.py", line 13, in <module>
    from .. import lib
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\ants\lib\__init__.py", line 4, in <module>
    from .antiAlias import *
ModuleNotFoundError: No module named 'ants.lib.antiAlias'

```

My environment is:
```
Win10
Anaconda
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
```

How to fix this bug? Any suggestion is appreciated!

**Comment by stnava** [comment]
this is not a working wheel - pypi has not approved this

https://github.com/pypa/pypi-support/issues/52
