### ISSUE TITLE
Issue with building ANTsPyNet in Docker

### ISSUE THREAD

**Issue by vnckppl** [ANTsX/ANTsPy#156]
**Describe the bug**
I am building a Docker image with ANTsPy and ANTsPyNet. ANTsPy builds just fine, but ANTsPyNet throws an error during the build process (see below).

During building ANTsPyNet, it searches for ants:

> Installed /usr/local/lib/python3.6/dist-packages/Keras-2.3.1-py3.6.egg
> Searching for ants
> Reading https://pypi.python.org/simple/ants/
> Downloading https://files.pythonhosted.org/packages/97/1a/71d058169f353007d21afa242a4a1490604af31c3888f8beec5a82f007cd/ants-0.0.7.tar.gz#sha256=21bc5a4ae78f17ef3f2be5d45173ce71670ff1f1b51988d5741259405b741670
> Best match: ants 0.0.7
> Processing ants-0.0.7.tar.gz
> Writing /tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.cfg
> Running ants-0.0.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-x5q0mfcq/ants-0.0.7/egg-dist-tmp-7kog2z04

After this line, the building breaks. 

I am wondering why, and why ANTsPyNet does not detect the ANTsPy that was successfully installed during the previous Docker step (see Docker file below)?

**To Reproduce**
Dockerfile build file:
```
### Install Dependencies
FROM ubuntu:bionic

RUN \
        apt-get update && \
        apt-get dist-upgrade -y --no-install-recommends && \
        apt-get install -y \
        build-essential \
        cmake \
        curl \
        g++ \
        gfortran \
        git \
        gnupg2 \
        libblas-dev \
        libglu1-mesa \
        liblapack-dev \
        libx11-dev \
        libxi-dev \
        libxmu-dev \
        libxmu-headers \
        libxt-dev \
        python3 \
        python3-pip \
        rs \
        tcsh \
        unzip \
        wget \
        zlib1g \
        zlib1g-dev

# Set up the environment
ENV PATH=${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

###############
### Python  ###
###############
RUN \
        python3 -m pip install \
        nipype \
        ipython \
        chart_studio \
        matplotlib \
        Pillow \
        pyyaml \
        scikit-image \
        scikit-learn \
        sklearn \
        statsmodels \
        webcolors \
        pandas \
        nilearn \
        scipy \
        svgutils \
        tensorflow

############
### ANTS ###
############
### Install ANTsPy
RUN \
        cd /software && \
        git clone https://github.com/ANTsX/ANTsPy && \
        cd /software/ANTsPy && \
        python3 setup.py install

RUN \
        cd /software && \
        git clone https://github.com/ANTsX/ANTsPyNet && \
        cd /software/ANTsPyNet && \
        python3 setup.py install

### Run
ENTRYPOINT ["python3", "/some/path/to/file.py"]

```

**Error Message**
```
Step 10/14 : RUN         cd /software &&         git clone https://github.com/ANTsX/ANTsPyNet &&         cd /software/ANTsPyNet &&         python3 setup.py install
 ---> Running in fa01cb9fb4e5
Cloning into 'ANTsPyNet'...
running install
running bdist_egg
running egg_info
creating antspynet.egg-info
writing antspynet.egg-info/PKG-INFO
writing dependency_links to antspynet.egg-info/dependency_links.txt
writing requirements to antspynet.egg-info/requires.txt
writing top-level names to antspynet.egg-info/top_level.txt
writing manifest file 'antspynet.egg-info/SOURCES.txt'
reading manifest file 'antspynet.egg-info/SOURCES.txt'
writing manifest file 'antspynet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/antspynet
creating build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_image_super_resolution_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_alexnet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_autoencoder_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_wasserstein_gan_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_simple_classification_with_spatial_transformer_network_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_wide_resnet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_denseunet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_deep_back_projection_network_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_expanded_super_resolution_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_denoising_auto_encoder_super_resolution_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_deep_convolutional_gan_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_cycle_gan_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_resunet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_resnet_super_resolution_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_super_resolution_gan_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_vanilla_gan_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_improved_wasserstein_gan_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_custom_unet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_unet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_deep_denoise_super_resolution_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_resnet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_vgg_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_convolutional_autoencoder_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/__init__.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
copying build/lib/antspynet/architectures/create_densenet_model.py -> build/bdist.linux-x86_64/egg/antspynet/architectures
creating build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/super_resolution_utilities.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/mixture_density_utilities.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/spatial_transformer_network_utilities.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/get_pretrained_network.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/custom_metrics.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/regression_match_image.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/resample_tensor_utilities.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/attention_utilities.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/deep_embedded_clustering_utilities.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/denseunet_utilities.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/custom_normalization_layers.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/extract_image_patches.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/reconstruct_image_from_patches.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/utilities/__init__.py -> build/bdist.linux-x86_64/egg/antspynet/utilities
copying build/lib/antspynet/__init__.py -> build/bdist.linux-x86_64/egg/antspynet
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_image_super_resolution_model.py to create_image_super_resolution_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_alexnet_model.py to create_alexnet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_autoencoder_model.py to create_autoencoder_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_wasserstein_gan_model.py to create_wasserstein_gan_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_simple_classification_with_spatial_transformer_network_model.py to create_simple_classification_with_spatial_transformer_network_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_wide_resnet_model.py to create_wide_resnet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_denseunet_model.py to create_denseunet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_deep_back_projection_network_model.py to create_deep_back_projection_network_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_expanded_super_resolution_model.py to create_expanded_super_resolution_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_denoising_auto_encoder_super_resolution_model.py to create_denoising_auto_encoder_super_resolution_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_deep_convolutional_gan_model.py to create_deep_convolutional_gan_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_cycle_gan_model.py to create_cycle_gan_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_resunet_model.py to create_resunet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_resnet_super_resolution_model.py to create_resnet_super_resolution_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_super_resolution_gan_model.py to create_super_resolution_gan_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_vanilla_gan_model.py to create_vanilla_gan_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_improved_wasserstein_gan_model.py to create_improved_wasserstein_gan_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_custom_unet_model.py to create_custom_unet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_unet_model.py to create_unet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_deep_denoise_super_resolution_model.py to create_deep_denoise_super_resolution_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_resnet_model.py to create_resnet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_vgg_model.py to create_vgg_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_convolutional_autoencoder_model.py to create_convolutional_autoencoder_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/architectures/create_densenet_model.py to create_densenet_model.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/super_resolution_utilities.py to super_resolution_utilities.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/mixture_density_utilities.py to mixture_density_utilities.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/spatial_transformer_network_utilities.py to spatial_transformer_network_utilities.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/get_pretrained_network.py to get_pretrained_network.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/custom_metrics.py to custom_metrics.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/regression_match_image.py to regression_match_image.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/resample_tensor_utilities.py to resample_tensor_utilities.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/attention_utilities.py to attention_utilities.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/deep_embedded_clustering_utilities.py to deep_embedded_clustering_utilities.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/denseunet_utilities.py to denseunet_utilities.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/custom_normalization_layers.py to custom_normalization_layers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/extract_image_patches.py to extract_image_patches.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/reconstruct_image_from_patches.py to reconstruct_image_from_patches.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/utilities/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/antspynet/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying antspynet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antspynet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antspynet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antspynet.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antspynet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying antspynet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/antspynet-0.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing antspynet-0.0-py3.6.egg
creating /usr/local/lib/python3.6/dist-packages/antspynet-0.0-py3.6.egg
Extracting antspynet-0.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding antspynet 0.0 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/antspynet-0.0-py3.6.egg
Processing dependencies for antspynet==0.0
Searching for tensorflow-probability
Reading https://pypi.python.org/simple/tensorflow-probability/
Downloading https://files.pythonhosted.org/packages/ae/42/ee2711c9c025bf59d2adb7e93e6142a2661b2689bfc4171ec686bc980b53/tensorflow_probability-0.10.0rc0-py2.py3-none-any.whl#sha256=1b01976c8874f30e706d943ffc4b7b3b95db659f3ed547e0d0442bc89070564e
Best match: tensorflow-probability 0.10.0rc0
Processing tensorflow_probability-0.10.0rc0-py2.py3-none-any.whl
Installing tensorflow_probability-0.10.0rc0-py2.py3-none-any.whl to /usr/local/lib/python3.6/dist-packages
writing requirements to /usr/local/lib/python3.6/dist-packages/tensorflow_probability-0.10.0rc0-py3.6.egg/EGG-INFO/requires.txt
Adding tensorflow-probability 0.10.0rc0 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/tensorflow_probability-0.10.0rc0-py3.6.egg
Searching for keras
Reading https://pypi.python.org/simple/keras/
Downloading https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl#sha256=d08a57bd63546175f8f19232ba05906514d419da3e0af8ef7437fa1c11442e20
Best match: Keras 2.3.1
Processing Keras-2.3.1-py2.py3-none-any.whl
Installing Keras-2.3.1-py2.py3-none-any.whl to /usr/local/lib/python3.6/dist-packages
writing requirements to /usr/local/lib/python3.6/dist-packages/Keras-2.3.1-py3.6.egg/EGG-INFO/requires.txt
Adding Keras 2.3.1 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/Keras-2.3.1-py3.6.egg
Searching for ants
Reading https://pypi.python.org/simple/ants/
Downloading https://files.pythonhosted.org/packages/97/1a/71d058169f353007d21afa242a4a1490604af31c3888f8beec5a82f007cd/ants-0.0.7.tar.gz#sha256=21bc5a4ae78f17ef3f2be5d45173ce71670ff1f1b51988d5741259405b741670
Best match: ants 0.0.7
Processing ants-0.0.7.tar.gz
Writing /tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.cfg
Running ants-0.0.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-x5q0mfcq/ants-0.0.7/egg-dist-tmp-7kog2z04
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.py", line 32, in <module>
  File "/tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.py", line 12, in readme
  File "/tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.py", line 8, in read
    author_email='ntustison@gmail.com',
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 141: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    zip_safe=False)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 437, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.py", line 32, in <module>
  File "/tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.py", line 12, in readme
  File "/tmp/easy_install-x5q0mfcq/ants-0.0.7/setup.py", line 8, in read
    author_email='ntustison@gmail.com',
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 141: ordinal not in range(128)
The command '/bin/sh -c cd /software &&         git clone https://github.com/ANTsX/ANTsPyNet &&         cd /software/ANTsPyNet &&         python3 setup.py install' returned a non-zero code: 1

real	102m21.801s
user	0m18.918s
sys	0m33.058s
```

**Comment by ntustison** [comment]
I don't have much experience with Docker builds and I'm not sure that @stnava does either.  You might want to try other avenues to debug your issue.

**Comment by stnava** [comment]
you might try it now - I updated the setup.py which ( probably ) had an extraneous `ants` in it.

**Comment by vnckppl** [comment]
Thanks Brian, that fixed it. Now the build log shows:

```
Using /usr/local/lib/python3.6/dist-packages
Searching for antspyx==0.2.5
Best match: antspyx 0.2.5
Adding antspyx 0.2.5 to easy-install.pth file
```
