### ISSUE TITLE
IndexError: list index out of range for ants.atropos on 3d image

### ISSUE THREAD

**Issue by willi3by** [ANTsX/ANTsPy#174]
**Describe the bug**
When I try to run ants.atropos, I get the following error message:

```/opt/anaconda3/lib/python3.7/site-packages/ants/segmentation/atropos.py:142: UserWarning:
ERROR: Non-zero exit status!
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-60-cdbc40125040>", line 1, in <module>
    ants.atropos(a=mr_resamp, x=mask)
  File "/opt/anaconda3/lib/python3.7/site-packages/ants/segmentation/atropos.py", line 146, in atropos
    probimgs = [iio2.image_read(probsout[0])]
IndexError: list index out of range
```

**To Reproduce**
I get the error when I run the command on any 3d image (e.g. T1-weighted MRI)

**Expected behavior**
I would expect that the segmentation would work the same for 3d as 2d images to get tissue segmentations for MR images.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Version: latest version of ANTsPy, installed from master branch (python setup.py install)

**Comment by ntustison** [comment]
What's your command call?

**Comment by willi3by** [comment]
```
mask = ants.get_mask(mr, cleanup=0)
seg = ants.atropos(a=mr, x=mask)
```

I tried to keep it simple for initial testing. 

mr info is:
```
ANTsImage (RPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (512, 512, 34)
	 Spacing    : (0.3906, 0.3906, 4.0)
	 Origin     : (-91.5556, 74.2278, -110.7796)
	 Direction  : [ 0.995  -0.0997 -0.0096 -0.0946 -0.9665  0.2387  0.0331  0.2366  0.971 ]
```

Thanks

**Comment by ntustison** [comment]
The default MRF parameter is for 2-D images.  You have to also override that argument for 3-D images.

```
    m : string
        mrf parameters as a string, usually "[smoothingFactor,radius]" where
        smoothingFactor determines the amount of smoothing and radius determines
        the MRF neighborhood, as an ANTs style neighborhood vector eg "1x1x1"
        for a 3D image. The radius must match the dimensionality of the image,
        eg 1x1 for 2D and The default in ANTs is smoothingFactor=0.3 and
        radius=1. See Atropos for more options.
```

**Comment by willi3by** [comment]
I see, thank you for your prompt response!
