### ISSUE TITLE
installation fails on osx when ITK is not present

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPy#2]
points of failure

```
cd ANTsPy-master
```

should be

```
cd ANTsPy
```

itk clone/compile works until

```
[100%] Built target MGHIO-all
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:31 (file):
  file cannot create directory: /libs/lib/cmake/ITK-4.12.  Maybe need
  administrative privileges.


make: *** [install] Error 1
ITK_DIR:  /Users/bavants/code/ANTsPy/itkbuild
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    subprocess.check_call(['./configure_antspy.sh'], cwd=setup_py_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

which is related primarily to the line

```
  file cannot create directory: /libs/lib/cmake/ITK-4.12.  Maybe need
```

which suggests a need to define a local install directory, perhaps within ANTsPy.

also need to document how to install ITK in the environment such that ANTsPy can see it.

**Comment by ncullen93** [comment]
try `sudo python setup.py develop` for now and i'll work on it.

**Comment by ncullen93** [comment]
closed bc it's fixed
