### ISSUE TITLE
Pip install failed

### ISSUE THREAD

**Issue by EzrealK** [ANTsX/ANTsPy#293]
**Describe the bug**
`pip install antspyx`  failed.

**Screenshots**
```
  Building wheel for antspyx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/setup.py'"'"'; __file__='"'"'/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-wheel-uXLVJK
       cwd: /private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/
  Complete output (104 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  Configuring ITK
  No local ITK installation found... Building ITK now...
  Cloning into 'itksource'...
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
  ./scripts/configure_ITK.sh: line 29: cd: itksource: No such file or directory
  ./scripts/configure_ITK.sh: line 41: ./data/softwareVersions.csv: No such file or directory
  ./scripts/configure_ITK.sh: line 42: ./data/softwareVersions.csv: No such file or directory
  CMake Error: The source directory "/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/itksource" does not exist.
  Specify --help for usage, or press the help button on the CMake GUI.
  make: *** No targets specified and no makefile found.  Stop.
  Configuring ANTs core
  Cloning into 'pybind11'...
  fatal: unable to access 'https://github.com/stnava/pybind11.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
  Cloning into 'antsrepo'...
  Already on 'master'
  Your branch is up-to-date with 'origin/master'.
  Already up-to-date.
  Note: checking out '2251ca1dfca9d27a58623eb36784704a032d97a0'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:
  
    git checkout -b <new-branch-name>
  
  HEAD is now at 2251ca1... Merge pull request #1115 from ANTsX/KKDefaults
  Configuring ANTsPy library
  -- The C compiler identification is AppleClang 12.0.5.12050022
  -- The CXX compiler identification is AppleClang 12.0.5.12050022
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:10 (find_package):
    By not providing "FindITK.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "ITK", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "ITK" with any of
    the following names:
  
      ITKConfig.cmake
      itk-config.cmake
  
    Add the installation prefix of "ITK" to CMAKE_PREFIX_PATH or set "ITK_DIR"
    to a directory containing one of the above files.  If "ITK" provides a
    separate development package or SDK, be sure it has been installed.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/build/temp.macosx-11.5-x86_64-2.7/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/build/temp.macosx-11.5-x86_64-2.7/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/setup.py", line 181, in <module>
      classifiers=["Programming Language :: Python :: 3.6"],
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/setup.py", line 40, in run
      self.run_command("build_ext")
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/setup.py", line 106, in run
      self.build_extension(ext)
    File "/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/setup.py", line 142, in build_extension
      ["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/ants/lib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/n6/qn4d1pln7nl48v4slvf04swr0000gn/T/pip-install-3mJc4Q/antspyx/ants/lib/', '-DPYTHON_EXECUTABLE=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for antspyx
```

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version: 11.15.1

 - cmake version 3.21.1

**Additional context**

**Comment by stnava** [comment]
need python3
