### ISSUE TITLE
Can not write any transform

### ISSUE THREAD

**Issue by kondratevakate** [ANTsX/ANTsPy#295]
**I am not able to save any transform**

**To Reproduce**
>>> image = ants.image_read('test/t1.nii.gz')
>>> image2 = ants.image_read('test/t2.nii.gz')
>>> mytrf = ants.registration(image, image2,'Rigid')
>>> ants.write_transform(mytrf, 'sample_transform.mat')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mri/miniconda3/envs/brats/lib/python3.9/site-packages/ants/core/ants_transform_io.py", line 338, in write_transform
    libfn = utils.get_lib_fn("writeTransform%s" % (transform._libsuffix))
AttributeError: 'dict' object has no attribute '_libsuffix'

**Expected behavior**
I want to save *.mat file and use it for further transforms

>>> ants.__version__
'0.2.9'

**Comment by ntustison** [comment]
``mytrf`` is a dictionary type that contains the warped fixed and moving images in addition to the forward and inverse transforms.  You have to access those dictionary transform elements in order to write out the transform.  Also see the ``outprefix`` option to directly write out the transforms.

**Comment by kondratevakate** [comment]
thanks, that is how I do this


```shutil.copy(t1_to_sri['fwdtransforms'][0], args.output +'T1_to_SRI_fwd.mat')
shutil.copy(t1_to_sri['invtransforms'][0], args.output +'T1_to_SRI_inv.mat')
flair_sri = ants.apply_transforms( sri_n4, image_t1, transformlist = [t1_to_sri['fwdtransforms'][0]])```
