### ISSUE TITLE
Circular import error

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsPy#680]
Hey all, I'd like to push an analogous enhancement (Frangi's generalized "vesselness" filter) that I just [put in ANTsR](https://github.com/ANTsX/ANTsR/commit/f79b125da43d54ae3f6bd78e10c8fc0522dd0f7f).  However, even prior to testing out the proposed changes, I'm getting a circular import error just from a fresh install of ANTsPy on both my mac laptop (miniconda) and mac workstation (anaconda).  Any ideas?  Thanks.

```
>>> import ants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ntustison/Pkg/ANTsPy/ants/__init__.py", line 4, in <module>
    from .core import *
  File "/Users/ntustison/Pkg/ANTsPy/ants/core/__init__.py", line 1, in <module>
    from .ants_image_io import (image_header_info,
  File "/Users/ntustison/Pkg/ANTsPy/ants/core/ants_image_io.py", line 23, in <module>
    from ants.internal import get_lib_fn, short_ptype, infer_dtype
  File "/Users/ntustison/Pkg/ANTsPy/ants/internal.py", line 2, in <module>
    from ants import lib
ImportError: cannot import name 'lib' from partially initialized module 'ants' (most likely due to a circular import) (/Users/ntustison/Pkg/ANTsPy/ants/__init__.py)
```

**Comment by cookpa** [comment]
Definitely not #627 again, right?

**Comment by ntustison** [comment]
Oh, garbage.  It's too early and not enough sleep.  Much appreciated, @cookpa.
