### ISSUE TITLE
slicing broken

### ISSUE THREAD

**Issue by rueberger** [ANTsX/ANTsPy#719]
ants 0.5.3

load any image then

`img[0:-1]` will throw

```
File ~/.local/lib/python3.8/site-packages/ants/core/ants_image.py:509, in ANTsImage.__getitem__(self, idx)
    506         raise ValueError('images do not occupy same physical space')
    507     return self.numpy().__getitem__(idx.numpy().astype('bool'))
--> 509 ndim = len(idx)
    510 sizes = list(self.shape)
    511 starts = [0] * ndim

TypeError: object of type 'slice' has no len()```

and similarly for `img[0]`

**Comment by cookpa** [comment]
It looks like there are several issues with slicing


```
>>> import ants
>>> import numpy as np
>>> im_ants = ants.image_read('mni.nii.gz')
>>> im_np = im.numpy()
```

Slice along the first dimension:

```
>>> im_ants[100]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniforge/base/envs/antspy/lib/python3.11/site-packages/ants/core/ants_image.py", line 509, in __getitem__
    ndim = len(idx)
           ^^^^^^^^
TypeError: object of type 'int' has no len()
>>> im_np[100]
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
```

However, we can slice along the first dimension by adding a comma

```
>>> im_ants[100,]
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
```

which gives us a numpy array, not an antsImage.


Slicing with all three indices produces an image, but the direction matrix is always collapsed to identity

```
>>> im_ants[100,:,:]
ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (218, 182)
	 Spacing    : (1.0, 1.0)
	 Origin     : (126.0, -72.0)
	 Direction  : [1. 0. 0. 1.]

>>> ants.slice_image(im_ants, 0, 100)
ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (218, 182)
	 Spacing    : (1.0, 1.0)
	 Origin     : (126.0, -72.0)
	 Direction  : [-1.  0.  0.  1.]
```


Negative indices don't work:


```
>>> im_np[:,:,0:-10].shape
(182, 218, 172)
>>> im_ants[:,:,0:-10]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniforge/base/envs/antspy/lib/python3.11/site-packages/ants/core/ants_image.py", line 538, in __getitem__
    new_ptr = libfn(self.pointer, starts, sizes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: getItem3(): incompatible function arguments. The following argument types are supported:
    1. getItem3(arg0: ants.lib.AntsImageF3, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageF3
    2. getItem3(arg0: ants.lib.AntsImageF4, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageF3
    3. getItem3(arg0: ants.lib.AntsImageUC3, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageUC3
    4. getItem3(arg0: ants.lib.AntsImageUC4, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageUC3
    5. getItem3(arg0: ants.lib.AntsImageUI3, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageUI3
    6. getItem3(arg0: ants.lib.AntsImageUI4, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageUI3
    7. getItem3(arg0: ants.lib.AntsImageD3, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageD3
    8. getItem3(arg0: ants.lib.AntsImageD4, arg1: collections.abc.Sequence[int], arg2: collections.abc.Sequence[int], /) -> ants.lib.AntsImageD3

Invoked with types: ants.lib.AntsImageF3, list, list
```

**Comment by cookpa** [comment]
Thanks for the report @rueberger . I will try to get a release up soon
